### ISSUE TITLE
Accented characters are not retrieved correctly. There is an encoding issue.

### ISSUE THREAD

**Issue by Thierry69** [peterdey/xpdf-dll#1]
Accented characters are not retrieved correctly. There is an encoding issue.

ex :
[4945_240109082026_001.pdf](https://github.com/user-attachments/files/18023722/4945_240109082026_001.pdf)

**Comment by peterdey** [comment]
Please test the latest build: zip with the binary is here: [upload-artefacts.zip](https://github.com/peterdey/xpdf-dll/actions/runs/12243101043/artifacts/2295909311)

Note that this requires code changes (refer to README.md for full snippets)
* Function definition has changed (see README.md): lpTextOutput is now changed to Long
* lpTextOutput must now be passed using VarPtr - otherwise the returned string will have a NULL every second character.

It would help with testing if you can also provide a clean PDF - not a scanned OCR'd one.  The supplied PDF does not appear to be well OCR'd, and has quite a bit of junk in the text.

**Comment by peterdey** [comment]
Resolved in eecd306 (released in [v4.03-2](https://github.com/peterdey/pdftotext-dll/releases/tag/v4.03-2))
